In [380]:
from itertools import combinations
import numpy as np

In [390]:
A = np.matrix('1,2,3,4 ; 5,6,7,8 ; 9,10,11,12')
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [463]:
zewnetrzna(A,3)

[matrix([[15, 18, 21, 24]])]

In [462]:
### To działa
def zewnetrzna(A, k):
    liczba_wierszy = A.shape[0]
    zewn = []
    for kombinacja in itertools.combinations(range(liczba_wierszy), k):
        suma = np.sum(A[list(kombinacja)], axis=0)
        zewn.append(suma)
    return zewn

In [469]:
def symetryczna(A,k):
    liczba_wierszy = A.shape[0]
    zewn = []
    for kombinacja in itertools.combinations_with_replacement(range(liczba_wierszy), k):
        suma = np.sum(A[list(kombinacja)], axis=0)
        zewn.append(suma)  
    return zewn

In [470]:
symetryczna(A, 2)

[matrix([[2, 4, 6, 8]]),
 matrix([[ 6,  8, 10, 12]]),
 matrix([[10, 12, 14, 16]]),
 matrix([[10, 12, 14, 16]]),
 matrix([[14, 16, 18, 20]]),
 matrix([[18, 20, 22, 24]])]

In [ ]:
### jeśli runujesz to na macierzy A zauważ, że 2*v2 = v1+v3 :)